name: dylan-grant-portfolio
favicon: null
layout_spectrum: 0.025131070986390114
typography_spectrum: 0.06956157297827303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9854931912850589
  lightness: 0.38384580868296325
  saturation: 0.8132756473496556
  rhythmicContrast: 0.23639071849174798
purpose: []
